### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by drmarwat** [minitena/source#7]
hello,
I downloaded the iso to test but dont see any option to install minitena. How to install or invoke installer from terminal?

**Comment by nee-san** [comment]
dead project

**Comment by nee-san** [comment]
@drmarwat look https://januslinux.github.io

**Comment by drmarwat** [comment]
@nee-san are you the developer of this distribution... https://januslinux.github.io ? I will test it but do not see much of documentation about it .

**Comment by nee-san** [comment]
I will add documentation soon. Maybe today
